<?php

namespace Database\Seeders;

use App\Models\Organism;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class OrganismSeeder extends Seeder
{
    public function run()
    {
        $secretarias = [
            [
                'name' => 'Secretaría General',
                'type' => 'Secretaría',
                'description' => 'Asiste al Poder Ejecutivo en la coordinación y organización de las actividades de la Jefatura de Gabinete.',
                'functions' => 'Coordinación de actividades de la Jefatura de Gabinete. Asistencia al Poder Ejecutivo.',
                'address' => 'J. M. Estrada 599, Belén de Escobar',
                'phone' => '(0348) 443-0463',
                'email' => 'secretariageneral@escobar.gob.ar',
                'sort_order' => 1,
            ],
            [
                'name' => 'Agencia Municipal de Desarrollo Productivo de Escobar',
                'type' => 'Agencia',
                'description' => 'Promueve y fomenta el desarrollo del distrito, implementa políticas para el fortalecimiento de la economía local y el sector privado.',
                'functions' => 'Promoción del desarrollo productivo. Fortalecimiento de la economía local. Apoyo al sector privado.',
                'address' => 'Belgrano 657, Belén de Escobar',
                'phone' => '11 3726 1259',
                'email' => 'secretariaproduccion@escobar.gob.ar',
                'sort_order' => 2,
            ],
            [
                'name' => 'Secretaría Contravencional',
                'type' => 'Secretaría',
                'description' => 'Moderniza la administración del sistema de control sobre comercio, medio ambiente, obras y seguridad vial, fortaleciendo las instituciones para el juzgamiento de contravenciones e infracciones.',
                'functions' => 'Control sobre comercio, medio ambiente, obras y seguridad vial. Juzgamiento de contravenciones e infracciones.',
                'address' => 'Alberdi 526, Belén de Escobar',
                'phone' => '(11) 2175-3769',
                'email' => 'contravesc@escobar.gob.ar',
                'sort_order' => 3,
            ],
            [
                'name' => 'Secretaría de Ingresos Públicos',
                'type' => 'Secretaría',
                'description' => 'Gestiona la determinación, verificación, fiscalización y percepción de tributos municipales a través de AMIP, optimizando la recaudación para garantizar fondos para servicios esenciales.',
                'functions' => 'Determinación y fiscalización de tributos. Percepción de tributos municipales. Optimización de la recaudación.',
                'address' => 'Belgrano 657 (AMIP Belén)',
                'phone' => '(0348) 4262870',
                'email' => 'amip@escobar.gob.ar',
                'sort_order' => 4,
            ],
            [
                'name' => 'Subsecretaría de Inspección de Industria, Comercio, Obras Particulares y Espacios Públicos',
                'type' => 'Subsecretaría',
                'description' => 'Coordina los cuerpos de inspectores municipales en auditorías de Industria, Comercio, Obras, Medio Ambiente y Espacios Públicos. Gestiona habilitaciones y evaluación de impacto ambiental.',
                'functions' => 'Inspección de industria y comercio. Auditorías de obras particulares. Gestión de habilitaciones. Evaluación de impacto ambiental.',
                'address' => 'Belgrano 657, 1º piso, Belén de Escobar',
                'phone' => '11 7628 9856',
                'email' => 'subsecretariadeinspeccion@escobar.gob.ar',
                'sort_order' => 5,
            ],
            [
                'name' => 'Agencia Municipal de Transporte, Tránsito y Seguridad Vial',
                'type' => 'Agencia',
                'description' => 'Planifica e implementa acciones para mejorar el tránsito y desarrolla políticas de seguridad vial. Coordina, fiscaliza y promociona el desarrollo del transporte público.',
                'functions' => 'Planificación y mejora del tránsito. Políticas de seguridad vial. Coordinación del transporte público.',
                'address' => 'Av. 25 de Mayo 459 (1° piso), Belén de Escobar',
                'phone' => '11 2482-4266',
                'email' => 'transito@escobar.gob.ar',
                'sort_order' => 6,
            ],
            [
                'name' => 'Secretaría de Seguridad',
                'type' => 'Secretaría',
                'description' => 'Ejecuta la política pública de seguridad con Policía Municipal, Guardia Urbana y Centro de Monitoreo, coordinando con fuerzas de seguridad para brindar protección integral a los vecinos.',
                'functions' => 'Política pública de seguridad. Coordinación con fuerzas de seguridad. Protección integral a los vecinos.',
                'address' => 'Sucre 1549, Ingeniero Maschwitz',
                'phone' => '11 2476 8697',
                'email' => 'seguridad@escobar.gob.ar',
                'sort_order' => 7,
            ],
            [
                'name' => 'Secretaría de Educación',
                'type' => 'Secretaría',
                'description' => 'Gestiona y coordina las políticas educativas del municipio para garantizar el acceso y la calidad educativa en todo el distrito.',
                'functions' => 'Gestión de políticas educativas. Coordinación de acceso a educación. Garantía de calidad educativa.',
                'address' => 'Colectora Oeste Ramal Escobar 2098, Ing. Maschwitz',
                'phone' => '11 2791-1963',
                'email' => 'secretariadeeducacion@escobar.gob.ar',
                'sort_order' => 8,
            ],
            [
                'name' => 'Subsecretaría de Educación',
                'type' => 'Subsecretaría',
                'description' => 'Coordina las acciones educativas del municipio.',
                'functions' => 'Coordinación de acciones educativas municipales.',
                'address' => 'Cervantes 635, Belén de Escobar',
                'phone' => '11 2791-1963',
                'email' => 'subsecretariadeeducacion@escobar.gob.ar',
                'sort_order' => 9,
            ],
            [
                'name' => 'Subsecretaría de Cultura y Turismo',
                'type' => 'Subsecretaría',
                'description' => 'Implementa programas y políticas de interés comunitario, orientados a la preservación y promoción de la cultura y turismo escobarense.',
                'functions' => 'Programas culturales y turísticos. Preservación del patrimonio cultural. Promoción del turismo local.',
                'address' => 'Mitre 450, Belén de Escobar',
                'phone' => '11 2716 3202',
                'email' => 'cultura@escobar.gob.ar',
                'sort_order' => 10,
            ],
            [
                'name' => 'Secretaría de Gobierno',
                'type' => 'Secretaría',
                'description' => 'Desarrolla y fortalece las políticas comunales.',
                'functions' => 'Desarrollo de políticas comunales. Fortalecimiento institucional.',
                'address' => 'J. M. Estrada 599, Belén de Escobar',
                'phone' => '11 7615 9409',
                'email' => 'gobierno@escobar.gob.ar',
                'sort_order' => 11,
            ],
            [
                'name' => 'Secretaría de Desarrollo Social',
                'type' => 'Secretaría',
                'description' => 'Promueve el acceso a los derechos sociales a toda la comunidad de Escobar, con prioridad y especial atención a la población que se encuentra en situación de extrema vulnerabilidad.',
                'functions' => 'Promoción de derechos sociales. Atención a población vulnerable. Programas de asistencia social.',
                'address' => 'Colectora Este 659/677, Belén de Escobar',
                'phone' => '11 3293 4932',
                'email' => 'desarrollosocial@escobar.gob.ar',
                'sort_order' => 12,
            ],
            [
                'name' => 'Secretaría de Salud',
                'type' => 'Secretaría',
                'description' => 'Trabaja en mejorar la calidad de vida de los vecinos mediante la promoción de políticas sanitarias, la prevención de enfermedades y la mejora del funcionamiento del sistema de atención local.',
                'functions' => 'Promoción de políticas sanitarias. Prevención de enfermedades. Mejora del sistema de atención local.',
                'address' => 'Almirante Brown 3200, Garín (Hospital del Bicentenario)',
                'phone' => null,
                'email' => 'salud@escobar.gob.ar',
                'sort_order' => 13,
            ],
            [
                'name' => 'Secretaría de Hacienda y Producción',
                'type' => 'Secretaría',
                'description' => 'Planifica y administra los recursos presupuestarios del Municipio, coordina y supervisa la gestión del personal y mantiene actualizada la información sobre programación y ejecución presupuestaria.',
                'functions' => 'Planificación presupuestaria. Administración de recursos. Gestión del personal municipal.',
                'address' => 'J. M. Estrada 599, Belén de Escobar',
                'phone' => '(0348) 443-0490',
                'email' => 'hacienda@escobar.gob.ar',
                'sort_order' => 14,
            ],
            [
                'name' => 'Subsecretaría de Hábitat y Vivienda',
                'type' => 'Subsecretaría',
                'description' => 'Gestiona políticas de hábitat y acceso a la vivienda.',
                'functions' => 'Políticas de hábitat. Programas de vivienda. Mejoramiento habitacional.',
                'address' => '25 de mayo 459, 2do piso, Belén de Escobar',
                'phone' => '1135447092',
                'email' => 'habitatyvivienda@escobar.gob.ar',
                'sort_order' => 15,
            ],
            [
                'name' => 'Secretaría de Planificación e Infraestructura',
                'type' => 'Secretaría',
                'description' => 'Se encarga de planificar y ejecutar las obras de infraestructura desplegadas en el territorio, así como de controlar la prestación de los servicios públicos.',
                'functions' => 'Planificación de obras de infraestructura. Ejecución de obras públicas. Control de servicios públicos.',
                'address' => 'Hipólito Yrigoyen 743, Belén de Escobar',
                'phone' => '(0348) 443-0494',
                'email' => 'secretariadeplanificacioninfraestructura@escobar.gob.ar',
                'sort_order' => 16,
            ],
            [
                'name' => 'Secretaría de Planificación Territorial y Espacio Público',
                'type' => 'Secretaría',
                'description' => 'Planea y desarrolla políticas que mejoren los espacios públicos del partido. Integra a todas las áreas vinculadas al mejoramiento del hábitat con el fin de brindar una mejor calidad de vida y garantizar el acceso a la tierra y a la vivienda.',
                'functions' => 'Planificación territorial. Mejoramiento de espacios públicos. Políticas de acceso a tierra y vivienda.',
                'address' => 'Sucre 1550, Ing. Maschwitz',
                'phone' => null,
                'email' => 'licitacionesespaciospublicos@escobar.go.ar',
                'sort_order' => 17,
            ],
            [
                'name' => 'Subsecretaría de Escobar Sostenible',
                'type' => 'Subsecretaría',
                'description' => 'Promueve políticas de desarrollo sostenible en el municipio.',
                'functions' => 'Políticas de sostenibilidad. Desarrollo sustentable. Gestión ambiental.',
                'address' => 'Sucre 1550, Ing. Maschwitz',
                'phone' => '11 3731 9156',
                'email' => 'sostenible@escobar.gob.ar',
                'sort_order' => 18,
            ],
            [
                'name' => 'Secretaría Legal y Técnica',
                'type' => 'Secretaría',
                'description' => 'Presta asesoramiento jurídico a todas las áreas del Departamento Ejecutivo que lo precisen, dictamina sobre los proyectos de convenios, ordenanzas, y actos administrativos dictados por el Intendente Municipal. Representa mediante sus apoderados a la Municipalidad en todos los juicios.',
                'functions' => 'Asesoramiento jurídico. Dictámenes legales. Representación legal del municipio. Gestión de sumarios.',
                'address' => 'Estrada 599, Belén de Escobar',
                'phone' => '(0348) 443-0463',
                'email' => 'secretarialegalytecnica@escobar.gob.ar',
                'sort_order' => 19,
            ],
        ];

        foreach ($secretarias as $sec) {
            Organism::updateOrCreate(
                ['slug' => Str::slug($sec['name'])],
                $sec
            );
        }
    }
}
